FROM golang:alpine as go-build
RUN apk update
RUN apk add make
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . /app
RUN make server

FROM alpine:3
RUN mkdir /app
RUN mkdir /client
WORKDIR /app
COPY --from=go-build /app/scepserver-opt ./
RUN ./scepserver-opt ca -init
CMD ["./scepserver-opt"]
